"use client";

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";

type Item = { id:string; name:string; rarity:string; image:string; price:number };
type Result = { success:boolean; chance:number; roll:number; target:Item; resultItem:Item|null; inputItem:Item; inputValue:number; balanceTopUp:number; totalInputValue:number };
const MIN_CHANCE=0.1, SPIN_MS=4200;
const money=(v:number)=>new Intl.NumberFormat("ru-RU",{maximumFractionDigits:2}).format(v);
const chanceFor=(input:number,target:number)=>Math.max(MIN_CHANCE,Math.min(100,target>0?input/target*100:MIN_CHANCE));
const rarity:Record<string,string>={COMMON:"text-slate-300",UNCOMMON:"text-cyan-300",RARE:"text-blue-300",EPIC:"text-purple-300",LEGENDARY:"text-pink-300",ARCANE:"text-red-300",NAMELESS:"text-yellow-300"};

export default function UpgradePage(){
 const [inventory,setInventory]=useState<Item[]>([]),[targets,setTargets]=useState<Item[]>([]),[balance,setBalance]=useState(0);
 const [inputId,setInputId]=useState(""),[targetId,setTargetId]=useState(""),[topUp,setTopUp]=useState(0),[search,setSearch]=useState("");
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[spinning,setSpinning]=useState(false),[angle,setAngle]=useState(0),[result,setResult]=useState<Result|null>(null),[error,setError]=useState("");\n const [lockedAttempt,setLockedAttempt]=useState<{chance:number;topUp:number;target:Item}|null>(null);
 const input=inventory.find(x=>x.id===inputId)||null,target=targets.find(x=>x.id===targetId)||null;
 const inputValue=input?.price||0,total=inputValue+topUp,chance=target?chanceFor(total,target.price):MIN_CHANCE;\n const shownChance=lockedAttempt?.chance??chance,shownTarget=lockedAttempt?.target??target;
 const availableTargets=useMemo(()=>{const q=search.trim().toLowerCase();return targets.filter(x=>!!input&&x.price>input.price&&(q?x.name.toLowerCase().includes(q)||x.rarity.toLowerCase().includes(q):true));},[targets,input,search]);
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/upgrader",{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d.error||"Не удалось загрузить апгрейдер");setInventory(d.inventory||[]);setTargets(d.targets||[]);setBalance(Number(d.balance)||0);setTopUp(v=>Math.min(v,Number(d.balance)||0));return d.inventory||[]}catch(e){setError(e instanceof Error?e.message:"Ошибка загрузки");return []}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 function chooseInput(id:string){if(spinning)return;setInputId(id);setTargetId("");setResult(null);setError("");setLockedAttempt(null)}\n function snapTopUp(v:number){const max=Math.max(0,Math.floor(balance)),n=Math.max(0,Math.min(max,Math.round(v)));return n<=100?Math.round(n/5)*5:n<=500?Math.round(n/10)*10:Math.round(n/25)*25}
 function startRoulette(data:Result){const sector=Math.max(.36,data.chance*3.6),landing=data.success?Math.random()*Math.max(.1,sector-1)+.5:sector+1+Math.random()*Math.max(.1,359-sector-1);setSpinning(true);setAngle(v=>v+2160+landing);window.setTimeout(async()=>{setResult(data);setSpinning(false);const freshInventory=await load();if(data.success&&data.resultItem){const fresh=data.resultItem;const found=freshInventory.find((x:Item)=>x.id===fresh.id);if(found){setInputId(found.id);setTargetId("");setResult(data);}}setLockedAttempt(null)},SPIN_MS+100)}
 async function upgrade(){if(!input||!target||target.price<=input.price||topUp>balance||busy||spinning)return;const attemptTopUp=topUp,attemptChance=chanceFor(input.price+attemptTopUp,target.price),attemptTarget=target;setLockedAttempt({chance:attemptChance,topUp:attemptTopUp,target:attemptTarget});setBusy(true);setError("");setResult(null);try{const r=await fetch("/api/upgrader",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemId:input.id,targetId:target.id,balanceTopUp:attemptTopUp,idempotencyKey:crypto.randomUUID()})}),d=await r.json();if(!r.ok)throw Error(d.error||"Апгрейд не выполнен");setBalance(v=>Math.max(0,v-attemptTopUp));setTopUp(0);startRoulette(d)}catch(e){setLockedAttempt(null);setError(e instanceof Error?e.message:"Ошибка апгрейда")}finally{setBusy(false)}}
 const degrees=Math.max(.36,shownChance*3.6);
 return <main className="min-h-screen bg-[#04050a] px-2 pb-24 pt-3 text-white sm:px-4 lg:px-6"><div className="mx-auto max-w-[1180px]">
  <header className="mb-3 flex items-center justify-between rounded-2xl border border-violet-400/15 bg-[#0b0d15] px-4 py-3"><div><p className="text-[9px] font-black uppercase tracking-[.28em] text-violet-300">ZeonGGStore</p><h1 className="text-2xl font-black">Апгрейдер</h1></div><div className="text-right"><p className="text-[8px] uppercase tracking-widest text-slate-500">Баланс</p><b className="text-sm text-yellow-300">{money(balance)} Z</b></div></header>
  {error&&<div className="mb-3 rounded-xl border border-red-400/20 bg-red-500/10 p-3 text-xs font-bold text-red-200">{error}</div>}
  {loading?<div className="rounded-2xl border border-white/10 bg-white/[.02] p-10 text-center text-slate-400">Загружаем апгрейдер...</div>:<>
   <section className="rounded-3xl border border-violet-300/10 bg-[#0b0d15] p-3 sm:p-5">
    <div className="grid grid-cols-[minmax(82px,150px)_minmax(130px,1fr)_minmax(100px,180px)] items-center gap-2 sm:gap-6">
      <SelectedCard item={input} label="ТВОЙ СКИН" compact/>
      <div className="relative mx-auto w-full max-w-[390px] aspect-square"><div className="absolute inset-[4%] rounded-full p-[7px] shadow-[0_0_55px_rgba(124,58,237,.2)]" style={{background:`conic-gradient(from 0deg,#f97316 0deg ${degrees}deg,#6d28d9 ${degrees}deg 360deg)`}}><div className="h-full w-full rounded-full border border-white/10 bg-[#070910] p-[9%]"><div className="relative h-full w-full rounded-full bg-[radial-gradient(circle,rgba(124,58,237,.15),rgba(4,5,10,.98)_68%)]"><div className="absolute inset-0 flex flex-col items-center justify-center text-center"><span className="text-[7px] font-black uppercase tracking-[.25em] text-slate-500 sm:text-[9px]">Шанс</span><b className="text-3xl font-black sm:text-5xl">{shownChance.toFixed(shownChance<1?2:1)}%</b>{shownTarget&&<div className="relative mt-1 h-10 w-10 sm:h-16 sm:w-16"><Image src={shownTarget.image} alt={shownTarget.name} fill className="object-contain" sizes="64px" unoptimized/></div>}<span className="mt-1 text-[6px] font-black uppercase tracking-widest text-orange-300">WIN</span><span className="text-[6px] font-black uppercase tracking-widest text-violet-300">LOSE</span></div></div></div></div><div className="absolute left-1/2 top-0 z-30 h-full w-1 -translate-x-1/2" style={{transform:`translateX(-50%) rotate(${angle}deg)`,transformOrigin:"50% 50%",transition:spinning?`transform ${SPIN_MS}ms cubic-bezier(.08,.72,.12,1)`:"transform .2s ease-out"}}><div className="absolute left-1/2 top-0 h-7 w-[4px] -translate-x-1/2 rounded-full bg-white shadow-[0_0_14px_white] sm:h-11"/><div className="absolute left-1/2 top-0 -translate-x-1/2 border-l-[7px] border-r-[7px] border-t-[12px] border-l-transparent border-r-transparent border-t-white sm:border-l-[10px] sm:border-r-[10px] sm:border-t-[17px]"/></div></div>
      <SelectedCard item={shownTarget} label="ЦЕЛЕВОЙ СКИН" target/>
    </div>
    <div className="mt-3 grid gap-2 sm:grid-cols-3"><Stat label="Твой скин" value={input?`${money(input.price)} Z`:"—"}/><Stat label="Цель" value={target?`${money(target.price)} Z`:"—"}/><Stat label="Итого + доплата" value={`${money(total)} Z`}/></div>
    <div className="mt-3 rounded-xl border border-violet-300/10 bg-violet-500/[.04] p-3"><div className="mb-2 flex justify-between text-xs"><b>Увеличить шанс</b><b className="text-yellow-300">+{money(topUp)} Z</b></div><input type="range" min="0" max={Math.max(0,Math.floor(balance))} step="1" value={topUp} disabled={spinning||busy} onChange={e=>setTopUp(snapTopUp(Number(e.target.value)))} className="relative z-10 h-6 w-full cursor-pointer appearance-none bg-transparent disabled:cursor-not-allowed [&::-webkit-slider-runnable-track]:h-2 [&::-webkit-slider-runnable-track]:rounded-full [&::-webkit-slider-runnable-track]:bg-violet-950 [&::-webkit-slider-thumb]:-mt-[6px] [&::-webkit-slider-thumb]:h-5 [&::-webkit-slider-thumb]:w-5 [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:border-2 [&::-webkit-slider-thumb]:border-white [&::-webkit-slider-thumb]:bg-violet-500"/><div className="pointer-events-none -mt-4 flex justify-between px-2">{Array.from({length:21},(_,i)=><span key={i} className="h-3 w-px bg-white/35"/>)}</div><div className="mt-2 flex justify-between text-[8px] text-slate-500"><span>0 Z</span><span>Доступно {money(balance)} Z</span></div><div className="mt-2 flex gap-2">{[25,50,100].filter(v=>v<=balance).map(v=><button key={v} type="button" disabled={spinning||busy} onClick={()=>setTopUp(snapTopUp(v))} className="rounded bg-violet-500/15 px-2 py-1 text-[9px] font-bold text-violet-300">+{v} Z</button>)}</div></div>
    {result&&<div className={`mt-3 rounded-xl border p-3 text-center ${result.success?"border-emerald-400/20 bg-emerald-500/10":"border-red-400/20 bg-red-500/10"}`}><b className={result.success?"text-emerald-300":"text-red-300"}>{result.success?"УСПЕШНЫЙ АПГРЕЙД":"АПГРЕЙД НЕ УДАЛСЯ"}</b><p className="mt-1 text-xs">{result.success?result.resultItem?.name:`Потерян: ${result.inputItem.name}`}</p></div>}
    <button onClick={()=>void upgrade()} disabled={!input||!target||target.price<=input.price||busy||spinning} className="mt-3 w-full rounded-xl bg-violet-600 px-4 py-3 text-xs font-black uppercase tracking-widest disabled:cursor-not-allowed disabled:bg-white/10">{busy||spinning?"Рулетка...":"Сделать апгрейд"}</button>
   </section>
   <div className="mt-3 grid grid-cols-2 gap-3">
    <Panel title="ТВОЙ ИНВЕНТАРЬ"><div className="grid max-h-[270px] grid-cols-3 gap-2 overflow-y-auto sm:grid-cols-4 lg:grid-cols-5">{inventory.map(x=><ItemCard key={x.id} item={x} active={x.id===inputId} onClick={()=>chooseInput(x.id)}/>)}</div></Panel>
    <Panel title="ДОСТУПНЫЕ ЦЕЛИ"><input value={search} onChange={e=>setSearch(e.target.value)} disabled={!input} placeholder={input?`Только дороже ${money(input.price)} Z`:"Сначала выбери свой скин"} className="mb-2 w-full rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-[10px] outline-none placeholder:text-slate-600"/><div className="grid max-h-[238px] grid-cols-3 gap-2 overflow-y-auto sm:grid-cols-4 lg:grid-cols-5">{availableTargets.map(x=><ItemCard key={x.id} item={x} active={x.id===targetId} onClick={()=>{setTargetId(x.id);setResult(null)}}/>)}</div>{input&&!availableTargets.length&&<p className="py-8 text-center text-xs text-slate-500">Нет скинов дороже {money(input.price)} Z</p>}</Panel>
   </div>
  </>}</div></main>
}
function SelectedCard({item,label,compact,target}:{item:Item|null;label:string;compact?:boolean;target?:boolean}){return <div className={`text-center ${target?"":""}`}><p className="mb-1 text-[7px] font-black uppercase tracking-widest text-slate-500 sm:text-[9px]">{label}</p><div className={`relative mx-auto rounded-xl border ${item?(target?"border-orange-400/30 bg-orange-500/[.05]":"border-violet-400/30 bg-violet-500/[.06]"):"border-dashed border-white/10 bg-black/20"} ${compact?"h-24 w-full sm:h-32":"h-28 w-full sm:h-40"}`}><span className="absolute inset-0 flex items-center justify-center text-[8px] text-slate-600">{!item&&"Выбери"}</span>{item&&<Image src={item.image} alt={item.name} fill className="object-contain p-2" sizes="180px" unoptimized/>}</div>{item&&<><p className="mt-1 line-clamp-1 text-[9px] font-black sm:text-xs">{item.name}</p><p className="text-[9px] font-black text-yellow-300 sm:text-xs">{money(item.price)} Z</p></>}</div>}
function ItemCard({item,active,onClick}:{item:Item;active:boolean;onClick:()=>void}){return <button type="button" onClick={onClick} className={`rounded-lg border p-1.5 text-left transition ${active?"border-violet-400 bg-violet-500/15":"border-white/10 bg-black/20 hover:border-white/20"}`}><div className="relative h-14 sm:h-20"><Image src={item.image} alt={item.name} fill className="object-contain" sizes="100px" unoptimized/></div><p className={`line-clamp-1 text-[7px] font-black uppercase ${rarity[item.rarity]||"text-slate-300"}`}>{item.rarity}</p><p className="mt-0.5 line-clamp-1 text-[8px] font-bold">{item.name}</p><p className="text-[8px] font-black text-yellow-300">{money(item.price)} Z</p></button>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-violet-300/10 bg-[#0b0d15] p-3"><h2 className="mb-2 text-[9px] font-black uppercase tracking-[.16em] text-slate-300">{title}</h2>{children}</section>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-white/10 bg-black/20 p-2"><p className="text-[7px] uppercase tracking-widest text-slate-500">{label}</p><p className="text-[10px] font-black sm:text-xs">{value}</p></div>}
