"use client";

import { useEffect, useState, type CSSProperties } from "react";

type Item = { id: string; name: string; rarity: string; image: string };
type Phase = "idle" | "burst" | "gather";
type Particle = { id: number; x: number; y: number; size: number; rotate: number; delay: number; sourceX: number; sourceY: number };
const BURST_MS = 2200;
const GATHER_MS = 2200;
const cache = new Map<string, { hex: string; rgb: string }>();
function rarityGlow(rarity: string) { const key=rarity.trim().toLowerCase(); if(key.includes("nameless"))return{hex:"#ff3b30",rgb:"255,59,48"}; if(key.includes("arcana"))return{hex:"#ff7a18",rgb:"255,122,24"}; if(key.includes("legendary"))return{hex:"#ffd21f",rgb:"255,210,31"}; if(key.includes("epic"))return{hex:"#c14dff",rgb:"193,77,255"}; if(key.includes("rare"))return{hex:"#3b82f6",rgb:"59,130,246"}; if(key.includes("uncommon"))return{hex:"#22c55e",rgb:"34,197,94"}; return{hex:"#9ca3af",rgb:"156,163,175"}; }
function detectColor(src:string,fallback:{hex:string;rgb:string}){if(typeof window==="undefined")return Promise.resolve(fallback);const saved=cache.get(src);if(saved)return Promise.resolve(saved);return new Promise<{hex:string;rgb:string}>(resolve=>{const image=new window.Image();image.crossOrigin="anonymous";image.onload=()=>{try{const canvas=document.createElement("canvas");canvas.width=canvas.height=48;const ctx=canvas.getContext("2d",{willReadFrequently:true});if(!ctx)return resolve(fallback);const scale=Math.min(48/image.naturalWidth,48/image.naturalHeight),w=image.naturalWidth*scale,h=image.naturalHeight*scale;ctx.drawImage(image,(48-w)/2,(48-h)/2,w,h);const pixels=ctx.getImageData(0,0,48,48).data;let best:[number,number,number,number]|null=null;for(let i=0;i<pixels.length;i+=16){const r=pixels[i],g=pixels[i+1],b=pixels[i+2],a=pixels[i+3];if(a<80)continue;const max=Math.max(r,g,b),min=Math.min(r,g,b),sat=max===0?0:(max-min)/max;if(sat<.18)continue;const score=sat*255+Math.abs((r+g+b)/3-128)*.2;if(!best||score>best[3])best=[r,g,b,score]}const color=best?{hex:`#${best[0].toString(16).padStart(2,"0")}${best[1].toString(16).padStart(2,"0")}${best[2].toString(16).padStart(2,"0")}`,rgb:`${best[0]},${best[1]},${best[2]}`} : fallback;cache.set(src,color);resolve(color)}catch{resolve(fallback)}};image.onerror=()=>resolve(fallback);image.src=src})}
function FragmentSet({item,particles,side,phase}:{item:Item;particles:Particle[];side:"left"|"right";phase:Phase}){const fallback=rarityGlow(item.rarity),[glow,setGlow]=useState(fallback),safeImage=item.image.replace(/"/g,"%22");useEffect(()=>{let cancelled=false;void detectColor(item.image,fallback).then(color=>{if(!cancelled)setGlow(color)});return()=>{cancelled=true}},[item.image,item.rarity]);return <>{particles.map(p=>{const sideOffset=side==="left"?-300:300,startX=side==="left"?18+p.sourceX*.62:82-(100-p.sourceX)*.62,startY=18+p.sourceY*.64,bx=p.x+sideOffset,by=p.y;const style:CSSProperties&Record<string,string>={width:`${p.size}px`,height:`${Math.max(12,p.size*.72)}px`,left:`calc(${startX}% - ${p.size/2}px)`,top:`calc(${startY}% - ${p.size*.36}px)`,backgroundImage:`url("${safeImage}")`,backgroundSize:"200px 130px",backgroundRepeat:"no-repeat",backgroundPosition:`${-(p.sourceX/100)*200}px ${-(p.sourceY/100)*130}px`,animationDelay:`${p.delay}ms`,"--bx":`${bx}px`,"--by":`${by}px`,"--gx":`${-bx}px`,"--gy":`${-by}px`,"--r":`${p.rotate}deg`,"--glow":glow.hex,"--glow-rgb":glow.rgb};return <span key={`${side}-${item.id}-${phase}-${p.id}`} className={`upgrade-fragment ${phase==="gather"?"upgrade-fragment-gather":"upgrade-fragment-burst"}`} style={style}/>})}</>}
export default function UpgradeFragmentLayer({leftItem,rightItem,phase,particles}:{leftItem:Item|null;rightItem:Item|null;phase:Phase;particles:Particle[]}){if(phase==="idle"||particles.length===0)return null;return <div className="pointer-events-none absolute inset-0 z-40 overflow-visible">{leftItem&&phase==="burst"&&<FragmentSet item={leftItem} particles={particles} side="left" phase="burst"/>}{rightItem&&<FragmentSet item={rightItem} particles={particles} side="right" phase={phase}/>}<style jsx>{`.upgrade-fragment{position:absolute;display:block;border-radius:4px;opacity:0;border:1px solid rgba(var(--glow-rgb),.32);box-shadow:0 0 14px rgba(var(--glow-rgb),.52),0 0 30px rgba(var(--glow-rgb),.24),0 0 2px var(--glow);will-change:transform,opacity,filter}.upgrade-fragment-burst{animation:burst ${BURST_MS}ms cubic-bezier(.12,.72,.16,1) forwards}.upgrade-fragment-gather{animation:gather ${GATHER_MS}ms cubic-bezier(.16,.78,.18,1) forwards}@keyframes burst{0%{opacity:0;transform:translate(0,0) rotate(0deg) scale(1)}8%{opacity:1}48%{opacity:1}100%{opacity:0;transform:translate(var(--bx),var(--by)) rotate(var(--r)) scale(.55);filter:brightness(.65) saturate(.9)}}@keyframes gather{0%{opacity:0;transform:translate(var(--bx),var(--by)) rotate(var(--r)) scale(.55);filter:brightness(.65) saturate(.9)}12%{opacity:1}68%{opacity:1}100%{opacity:0;transform:translate(var(--gx),var(--gy)) rotate(0deg) scale(1);filter:brightness(1.7) saturate(1.25)}}`}</style></div>}
