import { NextResponse } from "next/server";
import { randomInt } from "node:crypto";
import { getCurrentUser } from "@/lib/current-user";
import { prisma } from "@/lib/prisma";

type Difficulty = "easy" | "medium" | "hard";
type ActionBody = { action?: string; idempotencyKey?: string; difficulty?: Difficulty; stake?: number; mines?: number; gameId?: string; cell?: number };
type MineState = { current:number[]; revealed:Record<string,number[]> };
const CONFIG = { easy: { floors: 4, maxMultiplier: 2.5 }, medium: { floors: 8, maxMultiplier: 4.5 }, hard: { floors: 16, maxMultiplier: 6.75 } } as const;
const money=(n:number)=>Math.max(0,Math.floor(n));
const validDifficulty=(x:unknown):x is Difficulty=>x==="easy"||x==="medium"||x==="hard";
const factorFor=(d:Difficulty,mines:number)=>Math.pow(CONFIG[d].maxMultiplier,1/CONFIG[d].floors)**(mines/7);
const generateMines=(count:number)=>{const a=Array.from({length:8},(_,i)=>i);for(let i=a.length-1;i>0;i--){const j=randomInt(i+1);[a[i],a[j]]=[a[j],a[i]];}return a.slice(0,count).sort((x,y)=>x-y);};
const makeMineState=(current:number[],revealed:Record<string,number[]>={}):MineState=>({current,revealed});
const readMineState=(raw:string):MineState=>{try{const parsed=JSON.parse(raw||"[]");if(Array.isArray(parsed))return makeMineState(parsed);if(parsed&&Array.isArray(parsed.current)&&parsed.revealed&&typeof parsed.revealed==="object")return makeMineState(parsed.current,parsed.revealed as Record<string,number[]>);}catch{}throw new Error("GAME_STATE_INVALID");};
const serialize=(g:{id:string;difficulty:string;stake:number;currentAmount:number;floor:number;saveAvailable:boolean;errors:number;status:string;minesPerFloor:number;minePositions:string})=>{const state=readMineState(g.minePositions);return {gameId:g.id,difficulty:g.difficulty,stake:g.stake,currentAmount:g.currentAmount,floor:g.floor,floors:CONFIG[g.difficulty as Difficulty].floors,mines:g.minesPerFloor,saveAvailable:g.saveAvailable,errors:g.errors,multiplier:g.stake>0?Math.max(1,g.currentAmount/g.stake):1,status:g.status,revealedMines:state.revealed};};
export async function GET(){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const [u,g]=await Promise.all([prisma.user.findUnique({where:{id:user.id},select:{balance:true}}),prisma.towerGame.findFirst({where:{userId:user.id,status:"ACTIVE"},orderBy:{updatedAt:"desc"}})]);return NextResponse.json({balance:u?.balance??0,game:g?serialize(g):null});}
export async function POST(req:Request){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const b=await req.json().catch(()=>null) as ActionBody;if(!b)return NextResponse.json({error:"INVALID_BODY"},{status:400});const action=b.action;const key=typeof b.idempotencyKey==="string"?b.idempotencyKey.slice(0,100):"";if(!key)return NextResponse.json({error:"IDEMPOTENCY_KEY_REQUIRED"},{status:400});if(!["start","pick","cashout"].includes(action??""))return NextResponse.json({error:"INVALID_ACTION"},{status:400});if(await prisma.operation.findUnique({where:{idempotencyKey:key}}))return NextResponse.json({ok:true,replay:true});
try{
if(action==="start"){if(!validDifficulty(b.difficulty))throw new Error("INVALID_DIFFICULTY");const d=b.difficulty;const stake=money(Number(b.stake));if(stake<10)throw new Error("MIN_STAKE_10");const result=await prisma.$transaction(async tx=>{if(await tx.towerGame.findFirst({where:{userId:user.id,status:"ACTIVE"}}))throw new Error("ACTIVE_GAME_EXISTS");const u=await tx.user.findUnique({where:{id:user.id},select:{balance:true}});if(!u||u.balance<stake)throw new Error("INSUFFICIENT_BALANCE");const requested=Math.floor(Number(b.mines));const mines=d==="hard"?randomInt(4,8):Math.min(7,Math.max(1,Number.isFinite(requested)?requested:1));const updated=await tx.user.updateMany({where:{id:user.id,balance:{gte:stake}},data:{balance:{decrement:stake}}});if(updated.count!==1)throw new Error("BALANCE_CHANGED");const g=await tx.towerGame.create({data:{userId:user.id,difficulty:d,stake,currentAmount:stake,floor:0,minesPerFloor:mines,minePositions:JSON.stringify(makeMineState(generateMines(mines))),saveAvailable:d==="hard",errors:0,status:"ACTIVE"}});await tx.operation.create({data:{userId:user.id,type:"TOWER_START",amount:-stake,status:"SUCCESS",label:`Башня: старт ${d}`,idempotencyKey:key}});return{game:serialize(g),balance:u.balance-stake};});return NextResponse.json({ok:true,...result});}
const gameId=typeof b.gameId==="string"?b.gameId:"";if(!gameId)throw new Error("GAME_REQUIRED");
if(action==="cashout"){const result=await prisma.$transaction(async tx=>{const g=await tx.towerGame.findFirst({where:{id:gameId,userId:user.id},select:{id:true,difficulty:true,stake:true,currentAmount:true,floor:true,minesPerFloor:true,minePositions:true,saveAvailable:true,errors:true,status:true}});if(!g)throw new Error("GAME_NOT_FOUND");if(g.status!=="ACTIVE"||g.floor<=0)throw new Error("GAME_NOT_ACTIVE");const up=await tx.towerGame.updateMany({where:{id:g.id,userId:user.id,status:"ACTIVE",floor:g.floor,currentAmount:g.currentAmount},data:{status:"CASHED_OUT",minePositions:g.minePositions}});if(up.count!==1)throw new Error("GAME_STATE_CHANGED");await tx.user.update({where:{id:user.id},data:{balance:{increment:g.currentAmount}}});const balance=(await tx.user.findUnique({where:{id:user.id},select:{balance:true}}))?.balance??0;await tx.operation.create({data:{userId:user.id,type:"TOWER_CASHOUT",amount:g.currentAmount,status:"SUCCESS",label:`Башня: забрано ${g.currentAmount} Z`,idempotencyKey:key}});return{game:serialize({...g,status:"CASHED_OUT"}),balance,payout:g.currentAmount};});return NextResponse.json({ok:true,...result});}
const result=await prisma.$transaction(async tx=>{const g=await tx.towerGame.findFirst({where:{id:gameId,userId:user.id},select:{id:true,difficulty:true,stake:true,currentAmount:true,floor:true,minesPerFloor:true,minePositions:true,saveAvailable:true,errors:true,status:true}});if(!g)throw new Error("GAME_NOT_FOUND");if(g.status!=="ACTIVE")throw new Error("GAME_NOT_ACTIVE");const d=g.difficulty as Difficulty;if(g.floor>=CONFIG[d].floors)throw new Error("GAME_ALREADY_FINISHED");const state=readMineState(g.minePositions);if(state.current.length!==g.minesPerFloor)throw new Error("GAME_STATE_INVALID");const cell=Math.floor(Number(b.cell));if(cell<0||cell>7||!Number.isInteger(cell))throw new Error("INVALID_CELL");const hit=state.current.includes(cell);const amount=g.currentAmount;let nextAmount=amount,nextFloor=g.floor,nextErrors=g.errors,nextSave=g.saveAvailable,nextStatus="ACTIVE";const revealed={...state.revealed};
if(hit){nextErrors++;revealed[String(g.floor)]=[...state.current];if(d==="hard"&&g.saveAvailable){nextAmount=money(amount*.25);nextSave=false;nextFloor++;}else if(d==="hard"){nextAmount=money(amount*.25);nextStatus="LOST";}else{nextAmount=money(amount*.75);nextFloor++;}}
else{nextAmount=Math.max(amount,money(amount*factorFor(d,g.minesPerFloor)));nextFloor++;if(nextFloor>=CONFIG[d].floors)nextStatus="COMPLETED";}
const nextPositions=JSON.stringify(makeMineState(nextStatus==="ACTIVE"?generateMines(g.minesPerFloor):[],revealed));const up=await tx.towerGame.updateMany({where:{id:g.id,userId:user.id,status:"ACTIVE",floor:g.floor,currentAmount:amount,errors:g.errors,saveAvailable:g.saveAvailable},data:{currentAmount:nextAmount,floor:nextFloor,minePositions:nextPositions,errors:nextErrors,saveAvailable:nextSave,status:nextStatus}});if(up.count!==1)throw new Error("GAME_STATE_CHANGED");await tx.operation.create({data:{userId:user.id,type:hit?"TOWER_MINE":"TOWER_STEP",amount:0,status:hit&&nextStatus==="LOST"?"FAILED":"SUCCESS",label:`Башня: ${hit?"мина":"этаж"} ${g.floor+1}`,idempotencyKey:key}});let balance:number|null=null;if(nextStatus==="COMPLETED"){await tx.user.update({where:{id:user.id},data:{balance:{increment:nextAmount}}});balance=(await tx.user.findUnique({where:{id:user.id},select:{balance:true}}))?.balance??0;await tx.operation.create({data:{userId:user.id,type:"TOWER_REWARD",amount:nextAmount,status:"SUCCESS",label:`Башня: выплата ${nextAmount} Z`,idempotencyKey:`${key}:reward`}});}return{game:serialize({...g,currentAmount:nextAmount,floor:nextFloor,saveAvailable:nextSave,errors:nextErrors,status:nextStatus,minePositions:nextPositions}),balance,payout:nextStatus==="COMPLETED"?nextAmount:0};});return NextResponse.json({ok:true,...result});
}catch(e){const code=e instanceof Error?e.message:"TOWER_FAILED";return NextResponse.json({error:code},{status:["INSUFFICIENT_BALANCE","BALANCE_CHANGED","GAME_STATE_CHANGED","GAME_NOT_ACTIVE","ACTIVE_GAME_EXISTS"].includes(code)?409:400});}}
