"use client";

import { useCallback, useEffect, useState } from "react";

type Difficulty = "easy" | "medium" | "hard";
type Game = { gameId: string; difficulty: Difficulty; stake: number; currentAmount: number; floor: number; floors: number; mines: number; saveAvailable: boolean; errors: number; multiplier: number; status: string; revealedMine?: number | null; message?: string };
const DIFFICULTIES = { easy: { title: "Лёгкий", floors: 4 }, medium: { title: "Средний", floors: 8 }, hard: { title: "Сложный", floors: 16 } } as const;
const money = (n:number) => Math.max(0, Math.floor(n)).toLocaleString("ru-RU");
const id = () => crypto.randomUUID();

export default function TowerPage() {
  const [difficulty,setDifficulty]=useState<Difficulty>("easy"); const [stake,setStake]=useState(10); const [mines,setMines]=useState(1);
  const [game,setGame]=useState<Game|null>(null); const [balance,setBalance]=useState(0); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [help,setHelp]=useState(false); const [result,setResult]=useState<string|null>(null);
  const load=useCallback(async()=>{ try { const r=await fetch("/api/tower",{cache:"no-store"}); const d=await r.json(); if(!r.ok) throw new Error(d.error||"Ошибка"); setBalance(Number(d.balance)||0); if(d.game){setGame(d.game);setDifficulty(d.game.difficulty); if(d.game.difficulty==="hard")setMines(d.game.mines);} } catch(e){setError(e instanceof Error?e.message:"Ошибка загрузки");}},[]);
  useEffect(()=>{void load();},[load]);
  async function call(body:Record<string,unknown>){const r=await fetch("/api/tower",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,idempotencyKey:id()})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Ошибка");return d;}
  async function start(){if(stake<10||stake>balance)return;setBusy(true);setError("");try{const d=await call({action:"start",difficulty,stake:Math.floor(stake)});setGame(d.game);setBalance(Number(d.balance)||0);}catch(e){setError(e instanceof Error?e.message:"Не удалось начать");}finally{setBusy(false);}}
  async function pick(cell:number){if(!game||game.status!=="ACTIVE"||busy)return;setBusy(true);setError("");try{const d=await call({action:"pick",gameId:game.gameId,cell,mines:game.difficulty==="hard"?undefined:mines});setGame(d.game);if(typeof d.balance==="number")setBalance(d.balance);setResult(d.game.status==="COMPLETED"?"complete":d.game.revealedMine!==null&&d.game.revealedMine!==undefined?"mine":"safe");}catch(e){setError(e instanceof Error?e.message:"Ошибка выбора");}finally{setBusy(false);}}
  async function cashout(){if(!game||game.floor<=0||game.status!=="ACTIVE"||busy)return;setBusy(true);setError("");try{const d=await call({action:"cashout",gameId:game.gameId});setGame(d.game);setBalance(Number(d.balance)||0);setResult("cashout");}catch(e){setError(e instanceof Error?e.message:"Не удалось забрать");}finally{setBusy(false);}}
  const isHard=(game?.difficulty??difficulty)==="hard"; const floors=game?.floors??DIFFICULTIES[difficulty].floors; const active=game?.floor??0; const running=game?.status==="ACTIVE"; const shownMines=isHard?(game?.mines??4):mines;
  const selector=<div className="grid grid-cols-7 gap-1">{[1,2,3,4,5,6,7].map(n=><button key={n} type="button" disabled={busy} onClick={()=>setMines(n)} className={`rounded-xl border py-2 font-black ${mines===n?"border-violet-400 bg-violet-500/20 text-white":"border-white/10 bg-white/[.03] text-slate-400"}`}>{n}</button>)}</div>;
  return <main className="mx-auto min-h-[calc(100vh-72px)] max-w-6xl px-4 pb-32 pt-6"><header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.24em] text-violet-300">ZeonGGStore · Games</p><div className="mt-2 flex items-center gap-3"><h1 className="text-3xl font-black text-white sm:text-5xl">Башня</h1><button onClick={()=>setHelp(true)} className="flex h-9 w-9 items-center justify-center rounded-full border border-white/10 text-white">?</button></div></div><div className="rounded-2xl border border-white/10 bg-[#101421] px-5 py-3"><p className="text-[10px] text-slate-500">БАЛАНС</p><p className="font-black text-white">{money(balance)} Z</p></div></header>
  {!game&&<section className="mb-5 grid gap-3 md:grid-cols-3">{(Object.keys(DIFFICULTIES) as Difficulty[]).map(x=><button key={x} onClick={()=>setDifficulty(x)} className={`rounded-3xl border p-5 text-left ${difficulty===x?"border-violet-400/40 bg-violet-500/10":"border-white/10 bg-[#0e1220]"}`}><b className="text-white">{DIFFICULTIES[x].title}</b><p className="mt-2 text-sm text-slate-400">{DIFFICULTIES[x].floors} этажей</p></button>)}</section>}
  <section className="grid gap-5 lg:grid-cols-[1fr_300px]"><div className="rounded-[30px] border border-violet-300/10 bg-[#0b0f19] p-4"><div className="space-y-2">{Array.from({length:floors},(_,i)=>floors-i-1).map(level=>{const current=running&&level===active;const done=!!game&&level<active;return <div key={level} className={`rounded-2xl border p-2 ${current?"border-violet-400/30":"border-white/5"}`}><div className="mb-2 flex justify-between px-2 text-xs"><span className="text-slate-500">ЭТАЖ {level+1}</span><span className="text-violet-300">{current?`${shownMines} мин`:done?"✓ Пройден":""}</span></div><div className="grid grid-cols-4 gap-2">{Array.from({length:8},(_,cell)=>{const mine=game?.revealedMine===cell;return <button key={cell} disabled={!current||busy} onClick={()=>void pick(cell)} className={`h-14 rounded-xl border font-black sm:h-16 ${mine?"border-red-400/40 bg-red-500/15 text-red-300":done?"border-emerald-400/25 bg-emerald-500/10 text-emerald-300":current?"border-violet-300/10 bg-[#151a2a] text-slate-400":"border-white/5 text-slate-700"}`}>{mine?"💣":done?"✓":"?"}</button>})}</div></div>})}</div>{error&&<div className="mt-4 rounded-2xl bg-red-500/10 p-4 text-red-300">{error}</div>}{result&&<div className="mt-4 rounded-2xl bg-white/[.04] p-4 text-center text-white">{result==="mine"?"💣 Мина. Сумма изменена по правилам режима.":result==="safe"?"✓ Безопасно. Следующий этаж открыт.":result==="cashout"?`💰 Забрано ${money(game?.currentAmount??0)} Z`:`🏆 Башня пройдена. Выплата ${money(game?.currentAmount??0)} Z`}</div>}</div>
  <aside className="h-fit rounded-[30px] border border-white/10 bg-[#0e1220] p-5">{!game?<><label className="text-xs font-black uppercase tracking-widest text-slate-500">Начальная ставка</label><input type="number" min={10} value={stake} onChange={e=>setStake(Math.max(0,Number(e.target.value)||0))} className="mt-2 w-full rounded-2xl border border-white/10 bg-[#151a2a] px-4 py-3 font-black text-white"/>{difficulty!=="hard"&&<div className="mt-5"><p className="mb-2 text-xs font-black uppercase tracking-widest text-slate-500">Количество мин: 1–7</p>{selector}<p className="mt-2 text-xs text-slate-500">На лёгком и среднем игрок сам выбирает количество мин по ТЗ.</p></div>}<button disabled={busy||stake<10||stake>balance} onClick={()=>void start()} className="mt-5 w-full rounded-2xl bg-violet-500 py-3 font-black text-white disabled:opacity-40">{busy?"Запуск…":"Начать Башню"}</button></>:<><div className="grid grid-cols-2 gap-2"><div className="rounded-2xl bg-white/[.03] p-3"><p className="text-xs text-slate-500">Начало</p><b className="text-white">{money(game.stake)} Z</b></div><div className="rounded-2xl bg-violet-500/10 p-3"><p className="text-xs text-slate-500">Сейчас</p><b className="text-white">{money(game.currentAmount)} Z</b></div></div><div className="mt-3 rounded-2xl bg-white/[.03] p-3"><p className="text-xs text-slate-500">Множитель</p><b className="text-2xl text-white">x{game.multiplier.toFixed(2)}</b></div>{running&&!isHard&&<div className="mt-4"><p className="mb-2 text-xs font-black uppercase tracking-widest text-slate-500">Мин на текущем этаже: 1–7</p>{selector}<p className="mt-2 text-xs text-slate-500">Можно менять перед каждым этажом.</p></div>}<div className="mt-4 rounded-2xl bg-white/[.03] p-3 text-sm text-slate-400">Мины: <b className="text-white">{isHard?`${shownMines} · фикс.`:shownMines}</b>{isHard&&<><br/>Сейв: <b className="text-white">{game.saveAvailable?"1 доступен":"нет"}</b></>}</div>{running&&<button disabled={busy||game.floor<=0} onClick={()=>void cashout()} className="mt-4 w-full rounded-2xl bg-emerald-500 py-3 font-black text-white disabled:opacity-40">Забрать {money(game.currentAmount)} Z</button>}{game.status!=="ACTIVE"&&<button onClick={()=>{setGame(null);setResult(null);setMines(1);void load();}} className="mt-4 w-full rounded-2xl bg-violet-500 py-3 font-black text-white">Новая игра</button>}</>}</aside></section>
  {help&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-lg rounded-[30px] bg-[#101421] p-6 text-slate-300"><button onClick={()=>setHelp(false)} className="float-right text-white">×</button><h2 className="text-2xl font-black text-white">Что такое Башня?</h2><p className="mt-4">Вы поднимаетесь по этажам и увеличиваете сумму. После успешного этажа можно забрать выигрыш.</p><p className="mt-3"><b className="text-white">Лёгкий и средний:</b> выбирайте от 1 до 7 мин перед каждым этажом.</p><p className="mt-3"><b className="text-white">Сложный:</b> 16 этажей и один сейв. Первый серьёзный промах уменьшает сумму на 75%, второй завершает игру.</p></div></div>}
  </main>;
}
