"use client";

import Image from "next/image";
import { useCallback, useEffect, useState } from "react";

type Withdrawal = { id: string; status: string; createdAt: string; user: { id: string; name: string | null; email: string }; item: { name: string; rarity: string; image: string; price: number } | null; details: { gameId?: string; listingSkinName?: string; listingPriceGold?: number } };
const statusText: Record<string, string> = { PENDING: "Ожидает", PROCESSING: "В работе", SUCCESS: "Выполнен", CANCELED: "Отменён" };
export default function WithdrawalPanel() {
  const [items, setItems] = useState<Withdrawal[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const r = await fetch("/api/admin/withdrawals", { cache: "no-store" }); const j = await r.json(); if (!r.ok) throw new Error(j?.error || "Не удалось загрузить выводы"); setItems(j.withdrawals); } catch (e) { setError(e instanceof Error ? e.message : "Ошибка"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const update = async (id: string, status: string) => { const note = status === "CANCELED" ? window.prompt("Причина отмены (необязательно):", "") ?? "" : ""; const r = await fetch("/api/admin/withdrawals", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status, note }) }); const j = await r.json(); if (!r.ok) { setError(j?.error || "Не удалось обновить заявку"); return; } await load(); };
  return <div><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black">Выводы скинов</h2><p className="mt-1 text-sm text-slate-400">Заявки на передачу выигранных предметов через внутриигровой рынок.</p></div><button onClick={() => void load()} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-bold">Обновить</button></div>{error && <div className="mt-4 rounded-xl border border-red-400/20 bg-red-500/10 p-3 text-sm text-red-200">{error}</div>}{loading ? <p className="mt-6 text-sm text-slate-400">Загружаем...</p> : !items.length ? <p className="mt-6 text-sm text-slate-400">Заявок пока нет.</p> : <div className="mt-6 grid gap-4">{items.map((w) => <article key={w.id} className="rounded-2xl border border-white/10 bg-slate-900/70 p-4"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex min-w-0 items-center gap-3">{w.item && <div className="relative h-16 w-20 shrink-0"><Image src={w.item.image} alt="" fill className="object-contain" unoptimized /></div>}<div className="min-w-0"><div className="font-black">{w.item?.name || "Предмет удалён"}</div><div className="text-xs text-slate-400">{w.item?.price ?? 0} Z · {statusText[w.status] || w.status}</div><div className="mt-1 truncate text-xs text-slate-500">Игрок: {w.user.name || w.user.email} · ID {w.user.id}</div></div></div><div className="grid gap-1 text-xs text-slate-300 md:text-right"><span>Game ID: <b className="text-white">{w.details.gameId || "—"}</b></span><span>Выставит: <b className="text-white">{w.details.listingSkinName || "—"}</b></span><span>Цена: <b className="text-white">{w.details.listingPriceGold ?? "—"} Gold</b></span></div></div>{["PENDING", "PROCESSING"].includes(w.status) && <div className="mt-4 flex flex-wrap gap-2 border-t border-white/10 pt-3"><button onClick={() => void update(w.id, "PROCESSING")} className="rounded-xl bg-violet-600 px-3 py-2 text-xs font-black">Взять в работу</button><button onClick={() => void update(w.id, "SUCCESS")} className="rounded-xl bg-emerald-500/15 px-3 py-2 text-xs font-black text-emerald-200">Подтвердить получение</button><button onClick={() => void update(w.id, "CANCELED")} className="rounded-xl border border-red-400/20 px-3 py-2 text-xs font-black text-red-200">Отменить</button></div>}</article>)}</div>}</div>;
}
