"use client";

import Image from "next/image";
import Link from "next/link";
import { useSession } from "next-auth/react";
import { useEffect, useMemo, useState } from "react";

type ProfileUser = { id: string; email: string; name: string | null; avatar: string | null; createdAt: string; balance: number; role: "USER" | "ADMIN" | "DEV" | "NPN1_DEV" };
type InventoryItem = { id: string; name: string; rarity: string; image: string; price: number; addedAt: string };
type Operation = { id: string; type: string; label: string | null; amount: number; status: string; createdAt: string; item?: { name: string } | null };
type ProfileResponse = { user: ProfileUser; inventory: InventoryItem[]; operations: Operation[] };
type Statistics = { inventoryCount: number; inventoryValue: number; openedCases: number; soldItems: number; spent: number; earned: number };

const nav = [["Профиль", "/account", "profile"],["Инвентарь", "/account/inventory", "inventory"],["История", "/account/operations", "history"],["Статистика", "/account/statistics", "statistics"],["Поддержка", "/account/support", "support"],["Настройки", "/account/settings", "settings"]] as const;
const formatNumber = (value: number) => new Intl.NumberFormat("ru-RU", { maximumFractionDigits: 2 }).format(value);
const formatDate = (value: string) => new Intl.DateTimeFormat("ru-RU", { day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(value));
const formatDateTime = (value: string) => new Intl.DateTimeFormat("ru-RU", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
function displayName(name: string | null | undefined, email: string | null | undefined) { if (name?.trim()) return name.trim(); const raw = email?.split("@")[0] || "Игрок"; return raw.split(/[._-]+/).filter(Boolean).map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" "); }
function Icon({ kind }: { kind: string }) { const base = { fill: "none", stroke: "currentColor", strokeWidth: 1.8, strokeLinecap: "round" as const, strokeLinejoin: "round" as const }; return <svg viewBox="0 0 24 24" className="h-6 w-6" aria-hidden="true">{kind === "profile" && <><circle {...base} cx="12" cy="8" r="3.5" /><path {...base} d="M4.5 20a7.5 7.5 0 0 1 15 0" /></>}{kind === "inventory" && <><path {...base} d="m4 8 8-4 8 4-8 4-8-4Z" /><path {...base} d="M4 8v8l8 4 8-4V8M12 12v8" /></>}{kind === "history" && <><circle {...base} cx="12" cy="12" r="8.5" /><path {...base} d="M12 7v5l3.5 2" /></>}{kind === "statistics" && <path {...base} d="M5 19V11M12 19V6M19 19V3M3 20h18" />}{kind === "support" && <><path {...base} d="M4 13v-1a8 8 0 0 1 16 0v1M4 13h3v6H4v-6Zm16 0h-3v6h3v-6ZM8 20h5" /></>}{kind === "settings" && <><circle {...base} cx="12" cy="12" r="3" /><path {...base} d="m19 12 2-1-2-4-2 .5a7 7 0 0 0-2-1.2L14.5 4h-5L9 6.3a7 7 0 0 0-2 1.2L5 7l-2 4 2 1a7 7 0 0 0 0 2l-2 1 2 4 2-.5a7 7 0 0 0 2 1.2l.5 2.3h5l.5-2.3a7 7 0 0 0 2-1.2l2 .5 2-4-2-1a7 7 0 0 0 0-2Z" /></>}</svg>; }

export default function AccountProfile() {
  const { data: session } = useSession();
  const [data, setData] = useState<ProfileResponse | null>(null);
  const [statistics, setStatistics] = useState<Statistics | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { let cancelled = false; const load = async () => { setLoading(true); const [profileResult, statisticsResult] = await Promise.allSettled([fetch("/api/profile", { cache: "no-store" }), fetch("/api/statistics", { cache: "no-store" })]); if (cancelled) return; if (profileResult.status === "fulfilled" && profileResult.value.ok) setData(await profileResult.value.json()); if (statisticsResult.status === "fulfilled" && statisticsResult.value.ok) setStatistics(await statisticsResult.value.json()); setLoading(false); }; void load(); return () => { cancelled = true; }; }, []);
  const user = data?.user; const inventory = data?.inventory || []; const operations = data?.operations || []; const name = displayName(user?.name, user?.email || session?.user?.email);
  const bestDrop = useMemo(() => inventory.reduce<InventoryItem | null>((best, item) => !best || item.price > best.price ? item : best, null), [inventory]);
  const recentDrops = useMemo(() => [...inventory].sort((a,b) => new Date(b.addedAt).getTime() - new Date(a.addedAt).getTime()).slice(0,4), [inventory]);
  const recentOperations = useMemo(() => operations.slice(0,4), [operations]);
  const level = Math.max(1, Math.min(99, Math.floor(((statistics?.openedCases || 0) + (statistics?.soldItems || 0)) / 10) + 1)); const xp = Math.min(100, Math.round(((statistics?.openedCases || 0) % 10) * 10));
  const copy = async (value: string) => { if (value) await navigator.clipboard?.writeText(value); };
  return <main className="min-h-screen bg-[#05070c] text-white"><div className="mx-auto max-w-[1480px] px-3 pb-28 pt-4 sm:px-5 lg:px-7">
    <section className="overflow-hidden rounded-[26px] border border-violet-400/20 bg-[#0a0b13] shadow-[0_0_60px_rgba(124,58,237,0.13)]"><div className="relative grid min-h-[230px] gap-5 overflow-hidden p-5 sm:grid-cols-[1fr_auto] sm:p-7 lg:p-10"><div className="pointer-events-none absolute inset-0 opacity-80 [background:radial-gradient(circle_at_48%_38%,rgba(117,52,255,0.24),transparent_24%),radial-gradient(circle_at_70%_18%,rgba(77,29,130,0.22),transparent_28%)]" />
      <div className="relative flex min-w-0 items-center gap-4 sm:gap-6"><div className="flex h-28 w-28 shrink-0 items-center justify-center overflow-hidden rounded-[20px] border border-violet-300/30 bg-[linear-gradient(135deg,#1d0b31,#07070d)] shadow-[0_0_35px_rgba(138,54,255,0.28)] sm:h-36 sm:w-36">{user?.avatar || session?.user?.image ? <Image src={user?.avatar || session?.user?.image || ""} alt="Аватар" width={144} height={144} className="h-full w-full object-cover" /> : <span className="text-6xl font-black italic text-violet-300">Z</span>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-3"><h1 className="truncate text-3xl font-black tracking-[-0.05em] sm:text-4xl">{name}</h1><span className="rounded-full bg-violet-500/20 px-2 py-1 text-xs text-violet-200">◆</span></div><div className="mt-2 flex flex-wrap items-center gap-2 text-sm text-slate-400"><span>ID: {user?.id || "—"}</span><button onClick={() => void copy(user?.id || "")} className="rounded-md border border-white/10 px-2 py-0.5 text-xs hover:bg-white/5">⧉</button></div><div className="mt-6 flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-xl border border-violet-400/30 bg-violet-500/10 text-lg font-black text-violet-200">{level}</div><div className="min-w-0 max-w-[360px] flex-1"><div className="mb-2 flex justify-between text-xs font-bold text-violet-200"><span>{xp * 500} XP</span><span>50 000 XP</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-violet-500 shadow-[0_0_18px_rgba(168,85,247,.9)]" style={{ width: `${xp}%` }} /></div></div></div></div></div>
      <div className="relative flex min-w-[230px] flex-col justify-center rounded-[22px] border border-white/5 bg-black/20 p-6 sm:min-w-[280px]"><span className="text-xs font-black uppercase tracking-[0.14em] text-slate-400">Баланс</span><div className="mt-2 text-3xl font-black tabular-nums sm:text-4xl">{formatNumber(user?.balance || 0)} <span className="text-yellow-300">Z</span></div><Link href="/account" className="mt-5 rounded-xl bg-violet-600 px-5 py-3 text-center text-sm font-black uppercase tracking-wide shadow-[0_0_28px_rgba(124,58,237,.45)] transition hover:bg-violet-500">Пополнить</Link></div></div>
      <nav className="relative grid grid-cols-3 border-t border-white/10 bg-black/15 sm:grid-cols-6" aria-label="Навигация профиля">{nav.map(([label, href, kind]) => <Link key={href} href={href} className={`flex min-h-[74px] flex-col items-center justify-center gap-2 border-b border-white/5 px-2 text-center text-[10px] font-black uppercase tracking-wide transition sm:text-xs ${kind === "profile" ? "border-b-2 border-b-violet-400 bg-violet-500/[0.06] text-violet-300" : "text-slate-400 hover:bg-white/[0.03] hover:text-white"}`}><Icon kind={kind} /><span>{label}</span></Link>)}</nav></section>
    {loading ? <div className="mt-6 rounded-2xl border border-white/10 bg-white/[0.02] p-6 text-center text-slate-400">Загружаем профиль...</div> : <><div className="mt-6 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-[22px] border border-violet-300/15 bg-[#0c0d16] p-5"><h2 className="text-lg font-black uppercase tracking-wide">О себе</h2><div className="mt-4 divide-y divide-white/10 border-t border-white/10"><Info label="E-mail" value={user?.email || session?.user?.email || "—"} suffix="G" /><Info label="Дата регистрации" value={user?.createdAt ? formatDate(user.createdAt) : "—"} /><Info label="Бета-тест" value="УЧАСТНИК" accent /><Info label="Реферальный код" value={(user?.id || "ZEON").slice(0,10).toUpperCase()} copy={() => void copy((user?.id || "ZEON").slice(0,10).toUpperCase())} /><Info label="Реферальная ссылка" value={user ? `/r/${user.id}` : "—"} copy={() => void copy(`${window.location.origin}/r/${user?.id || ""}`)} /></div></section><section className="overflow-hidden rounded-[22px] border border-violet-300/15 bg-[#0c0d16]"><h2 className="border-b border-white/10 p-5 text-lg font-black uppercase tracking-wide">Лучший дроп</h2>{bestDrop ? <div className="grid min-h-[260px] grid-cols-[1.1fr_.9fr] items-center gap-3 p-5"><div className="relative h-[210px]"><Image src={bestDrop.image} alt={bestDrop.name} fill className="object-contain drop-shadow-[0_0_28px_rgba(255,60,90,.25)]" /></div><div><p className="text-sm text-yellow-300">★ {bestDrop.name.split(" ")[0]}</p><p className="mt-2 text-xl font-black">{bestDrop.name}</p><p className="mt-1 font-bold text-red-300">{bestDrop.rarity}</p><p className="mt-4 text-2xl font-black">{formatNumber(bestDrop.price)} <span className="text-yellow-300">Z</span></p><p className="mt-3 text-xs text-slate-500">Получен {formatDate(bestDrop.addedAt)}</p></div></div> : <div className="p-10 text-center text-slate-500">Пока нет дропов</div>}</section></div>
      <section className="mt-5 rounded-[22px] border border-violet-300/15 bg-[#0c0d16] p-5"><h2 className="text-lg font-black uppercase tracking-wide">Общая статистика</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Stat value={statistics?.openedCases || 0} label="Открыто кейсов" icon="▣" /><Stat value={statistics?.soldItems || 0} label="Продано предметов" icon="◎" /><Stat value={operations.filter((item) => item.type.toLowerCase().includes("tower")).length} label="Побед в башне" icon="◉" /><Stat value={statistics?.openedCases ? Math.min(100, Math.round((statistics.soldItems / statistics.openedCases) * 100)) : 0} suffix="%" label="Эффективность дропа" icon="◈" /><Stat value={statistics?.inventoryValue || 0} label="Сумма дропов" icon="◇" /></div></section>
      <div className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-[22px] border border-violet-300/15 bg-[#0c0d16] p-5"><h2 className="text-lg font-black uppercase tracking-wide">Недавние дропы</h2><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{recentDrops.map((item) => <div key={item.id} className="rounded-xl border border-white/8 bg-black/15 p-3"><div className="relative h-28"><Image src={item.image} alt={item.name} fill className="object-contain" /></div><p className="mt-2 line-clamp-2 text-sm font-bold">{item.name}</p><p className="mt-2 text-lg font-black">{formatNumber(item.price)} <span className="text-yellow-300">Z</span></p><p className="mt-1 text-xs text-slate-500">{formatDate(item.addedAt)}</p></div>)}</div><Link href="/account/inventory" className="mt-4 block rounded-xl border border-white/10 py-3 text-center text-sm font-black uppercase text-slate-300 hover:bg-white/5">Весь инвентарь</Link></section><section className="rounded-[22px] border border-violet-300/15 bg-[#0c0d16] p-5"><h2 className="text-lg font-black uppercase tracking-wide">Активность</h2><div className="mt-4 divide-y divide-white/10 border-t border-white/10">{recentOperations.map((operation) => <div key={operation.id} className="flex items-center justify-between gap-3 py-4"><div className="min-w-0"><p className="truncate font-bold">{operation.label || operation.item?.name || operation.type}</p><p className="mt-1 text-xs text-slate-500">{formatDateTime(operation.createdAt)}</p></div><p className={`shrink-0 font-black ${operation.amount >= 0 ? "text-emerald-300" : "text-red-300"}`}>{operation.amount >= 0 ? "+" : ""}{formatNumber(operation.amount)} Z</p></div>)}{recentOperations.length === 0 && <p className="py-8 text-center text-sm text-slate-500">Активности пока нет</p>}</div><Link href="/account/operations" className="mt-4 block rounded-xl border border-white/10 py-3 text-center text-sm font-black uppercase text-slate-300 hover:bg-white/5">Вся история</Link></section></div></>}</div></main>;
}
function Info({ label, value, suffix, accent, copy }: { label: string; value: string; suffix?: string; accent?: boolean; copy?: () => void }) { return <div className="flex min-h-14 items-center justify-between gap-4 py-3"><span className="text-sm font-semibold text-slate-400">{label}</span><div className="flex min-w-0 items-center gap-2 text-right text-sm font-bold"><span className={`truncate ${accent ? "rounded-lg bg-violet-500/15 px-2 py-1 text-violet-300" : "text-slate-100"}`}>{value}</span>{suffix && <span className="text-sm text-yellow-300">{suffix}</span>}{copy && <button onClick={copy} className="rounded-md border border-white/10 px-2 py-1 text-xs text-slate-400 hover:bg-white/5">⧉</button>}</div></div>; }
function Stat({ value, suffix = "", label, icon }: { value: number; suffix?: string; label: string; icon: string }) { return <div className="rounded-xl border border-white/5 bg-black/15 p-4"><div className="text-2xl text-violet-300">{icon}</div><p className="mt-2 text-2xl font-black">{formatNumber(value)}{suffix}</p><p className="mt-1 text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p></div>; }
